### ISSUE TITLE
riss (7.1) outputs blank line before s UNSATISFIABLE

### ISSUE THREAD

**Issue by jwaldmann** [conp-solutions/riss#16]
Hi,
```
(echo "p cnf 0 1" && echo "0"  ) | riss
...
c CPU time              : 0.000156 s

s UNSATISFIABLE
```
the blank line was confusing my parser. I thought that each line should start with `c`, `s` or `v`.

(I have `riss (core) 7.1.0    v7.1.0-dirty`, built from source in 2019.)

**Comment by conp-solutions** [comment]
This seems to be fixed in the latest revision, resolving.
